name: Push Tagged to Public Github
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  push:
    tags: 
    - "*"

jobs:
  Push-to-Github-on-Tag-Creation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Get the last tag
      - name: Get the previous and current tag
        id: get_tag
        run: |
          git fetch --tags --force
          CURRENT_TAG=$(git describe --tags --abbrev=0)
          PREVIOUS_TAG=$(git describe --tags $(git rev-list --tags --skip=1 --max-count=1) --abbrev=0) 2>/dev/null || git rev-list --max-parents=0 HEAD
          echo "Current tag is: $CURRENT_TAG"
          echo "Previous tag is: $PREVIOUS_TAG"
          echo "::set-output name=current_tag::$CURRENT_TAG"
          echo "::set-output name=previous_tag::$PREVIOUS_TAG"
      
      # Step 3: Squash commits between the last tag and the current HEAD
      - name: Squash commits
        run: |
          git config --global user.email "ross.mcwilliams@mahss.io"
          git config --global user.name ${{ secrets.USERNAME_GITHUB }}
          git checkout ${{ steps.get_tag.outputs.current_tag }}
          git reset --soft ${{ steps.get_tag.outputs.previous_tag }}
          git commit -m "Release ${{ steps.get_tag.outputs.current_tag }}"

      # Step 4: Push to another repository
      - name: Push to another repository
        env:
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
          TARGET_BRANCH: "master"  # Change if you need a different branch
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: |
          git remote add target-repo https://${{ env.USERNAME_GITHUB }}:${{ env.TOKEN_GITHUB }}@github.com/mahss-io/tplink-network-switch-hacs.git
          git push target-repo ${{ env.TARGET_BRANCH }}